services:
  - postgresql
  
platform:
  - Any CPU

configuration:
  - Release

assembly_info:
  patch: true

before_build:
  - cmd: set POSTGRES_HOST=127.0.0.1
  - cmd: set POSTGRES_DB=postgres
  - cmd: set POSTGRES_USER=postgres
  - cmd: set POSTGRES_PASS=Password12!
  - cmd: nuget restore Src\Stored.sln

build:
  project: Src\Stored.sln

on_success:
  - cmd: nuget pack Src\Stored\Stored.nuspec -NoDefaultExcludes -BasePath Src\Stored\bin\Release -OutputDirectory build -Version %appveyor_build_version%
  - cmd: nuget pack Src\Stored.Postgres\Stored.Postgres.nuspec -NoDefaultExcludes -BasePath Src\Stored.Postgres\bin\Release -OutputDirectory build -Version %appveyor_build_version%

artifacts:
  - path: 'build\*.nupkg'

test:
  assemblies:
    - '**\Stored.Tests.dll'

cache:
  - Src\packages -> **\packages.config