#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# ------

sh script/clean

# ------

version=${1:-1.0.0.0}

mkdir -p dist

# build project
dotnet build Src/Stored.sln
dotnet publish -o

# package
sh script/package ${version}

# --------
