#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# ------

sh script/clean

# ------

NUGET_VERSION=$(cat version.txt)

mkdir -p dist

# build project
dotnet build -c Release Src/Stored/Stored.csproj
dotnet build -c Release Src/Stored.Postgres/Stored.Postgres.csproj

# package
sh script/package ${NUGET_VERSION}

# --------
