#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# ------

sh script/clean

# ------

version=${1:-1.0.0.0}

mkdir -p dist

# build project
dotnet build -c Release Src/Stored/Stored.csproj
dotnet build -c Release Src/Stored.Postgres/Stored.Postgres.csproj

# package
sh script/package ${version}

# --------
