#!/bin/sh

# script/build - compiles the application.

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# ------

export POSTGRES_HOST=127.0.0.1
export POSTGRES_PORT=5432
export POSTGRES_DB=circle_test
export POSTGRES_USER=ubuntu

# ------

sh script/clean
sh script/bootstrap

# ------

version=${1:-1.0.0.0}

echo "-- BUILD --"

# build
xbuild Src/Stored.sln /target:Rebuild /property:Configuration=Release /property:Platform="Any CPU" /property:BUILD_VERSION=${version}

echo "-- TEST --"

# test
nuget install xunit.runner.console -Version 2.1.0 -o Src/packages
mono --runtime=v4.0 Src/packages/xunit.runner.console.2.1.0/tools/xunit.console.exe Src/Stored.Tests/bin/Release/Stored.Tests.dll -noappdomain

echo "-- PACKAGE --"

# package
sh script/package ${version}

echo "-- DONE --"

# --------
