#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# ------

version=${1:-1.0.0.0}

# nuget packaging
nuget pack Src/Stored/Stored.nuspec -NoDefaultExcludes -BasePath Src/Stored/bin/Release/netstandard2.0 -OutputDirectory dist -Version ${version}
nuget pack Src/Stored.Postgres/Stored.Postgres.nuspec -NoDefaultExcludes -BasePath Src/Stored.Postgres/bin/Release/netstandard2.0 -OutputDirectory dist -Version ${version}

# ------
