#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# ------

. script/vars

dotnet nuget push "dist/Stored.${NUGET_VERSION}.nupkg" -k ${NUGET_APIKEY} --source https://api.nuget.org/v3/index.json
dotnet nuget push "dist/Stored.Postgres.${NUGET_VERSION}.nupkg" -k ${NUGET_APIKEY} --source https://api.nuget.org/v3/index.json

# ------
