#!/bin/sh

# script/test - executes the tests.

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# --------

sh script/build

# --------

nuget install xunit.runners -Version 1.9.2 -o Src/packages
dotnet Src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe Src/Stored.Tests/bin/Release/Stored.Tests.dll

# --------
