#!/bin/sh

# script/test - executes the tests.

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# --------

sh script/build

# --------

nuget install xunit.runner.console -Version 2.1.0 -o Src/packages
mono --runtime=v4.0 Src/packages/xunit.runner.console.2.1.0/tools/xunit.console.exe Src/Stored.Tests/bin/Release/Stored.Tests.dll

# --------
